---


# Jira version.
jira_version: "8.7.1"

# Jira download details.
jira_download: "{{ _jira_download[jira_version] }}"

# MySQL JDBC version.
mysql_jdbc_version: "5.1.48"

# MySQL JDBC download details.
mysql_jdbc_download: "{{ _mysql_jdbc_download[mysql_jdbc_version] }}"

# PostgreSQL JDBC version.
postgresql_jdbc_version: "42.2.10"

# PostgreSQL JDBC download details.
postgresql_jdbc_download: "{{ _postgresql_jdbc_download[postgresql_jdbc_version] }}"

# Owner and group for Jira.
jira_owner: "jira"
jira_group: "jira"

# Jira home directory.
jira_home: "/var/atlassian/application-data/jira"

# Jira installation directory.
jira_catalina: "/opt/atlassian/jira"

# JVM minimal and maximum memory usage.
jira_jvm_minimum_memory: "1024m"
jira_jvm_maximum_memory: "1024m"

# Proxy and context path setup.
jira_catalina_connector_proxyname: ~
jira_catalina_connector_proxyport: ~
jira_catalina_connector_scheme: "http"
jira_catalina_connector_secure: "false"
jira_catalina_context_path: "/"

# Atlassian Support recommended JVM arguments.
jira_jvm_support_recommended_args: >-
  -Datlassian.plugins.enable.wait=300
  -XX:+UnlockExperimentalVMOptions
  -XX:MaxRAMFraction=1

# Variables for configuration
jira_templates:
      - { dest: "/etc/init.d/jira", mode: "0755" }
      - { dest: "/lib/systemd/system/jira.service" }
      - dest: "{{ jira_catalina }}/bin/setenv.sh"
        src: "./templates/opt/atlassian/jira/bin/setenv.sh.j2"
        owner: "{{ jira_owner }}"
        group: "{{ jira_group }}"
        mode: "0755"
      - dest: "{{ jira_catalina }}/conf/server.xml"
        src: "./templates/opt/atlassian/jira/conf/server.xml.j2"
        owner: "{{ jira_owner }}"
        group: "{{ jira_group }}"
      - dest: "{{ jira_catalina }}/dbconfig.xml"
        src: "./templates/opt/atlassian/jira/conf/dbconfig.xml.j2"
        owner: "{{ jira_owner }}"
        group: "{{ jira_group }}"

jira_files:
      - { dest: "/etc/init.d/jira", mode: "0755" }
      - { dest: "/lib/systemd/system/jira.service" }
      - dest: "{{ jira_catalina }}/bin/setenv.sh"
        owner: "{{ jira_owner }}"
        group: "{{ jira_group }}"
        mode: "0755"
      - dest: "{{ jira_catalina }}/conf/server.xml"
        owner: "{{ jira_owner }}"
        group: "{{ jira_group }}"
      - dest: "{{ jira_catalina }}/dbconfig.xml"
        owner: "{{ jira_owner }}"
        group: "{{ jira_group }}"

# Jira database

jira_session_timeout: "300"

jira_database_type: 'mysql'

jira_database_host: 'localhost'
jira_database_port: '3306'
jira_database_name: 'jiradb'

jira_database_url: "jdbc:mysql://{{ jira_database_host }}:{{ jira_database_port }}/{{ jira_database_name }}?useUnicode=true&amp;characterEncoding=UTF8&amp;sessionVariables=default_storage_engine=InnoDB"
jira_database_driver_class: 'com.mysql.jdbc.Driver'
jira_database_validation_query: 'select 1'
jira_database_validation_query_timeout: 3
jira_database_username: 'jira'
jira_database_password: 'jira'

